### ISSUE TITLE
New to-do list

### ISSUE THREAD

**Issue by itchyshin** [itchyshin/castration_meta-analysis#5]
Here are @itchyshin and @Mike-Garratt's to-do list

@itchyshin 

- [x] re-analyize the data set with lnRR - use arcsin transformation for % - http://strata.uga.edu/8370/rtips/proportions.html
- [ ] make a forest plot for Species
- [ ] Env x Sex interaction 
- [x] code to exclude Vasectomy
- [x] analysis for lnVR for mean data (this does not work - do hetero - test)
- [x] do sensitivity analysis excluding the influential study

@Mike-Garratt 

- [x] create a new variable of which sex live longer - Male, Female or Equal or something like that
- [x] check out the excel datasheet - I highlighted % data that needs to be turned into proportion
- [x] send Shinichi some papers to look at? (or maybe not).

Please add to the list if I forget something
