### ISSUE TITLE
To-do list (28 July 2021)

### ISSUE THREAD

**Issue by itchyshin** [itchyshin/castration_meta-analysis#7]
@itchyshin 
- [x] comparing (M/F) vs (CM/F), (F/M) vs (CF/M) and (M/F) vs (CM/CF) - but last one requires new data frame
- [ ] Full modeling - Sex, Env, Maturation, Gonad, Qualtiy, Effect_type 
- [ ] Sex specific modelling?
- [ ] Potental model selection
- [ ] Add SD or CV or the new data rows - imputation required

@Mike-Garratt 

- [x]  Adding O'Neil papers' data
- [ ] Adding Quality (controlled vs non)
- [x] Making a new datasheet for papers with both sexes castrated (see the other issue)
